export const categories = [
  "Electronics accesory",
  "Camera",
  "Car & Vehicle",
  "Cell Phone",
  "GPS",
  "Headphones",
  "Home Audio",
  "Security & Surveillance",
  "Wearable Technology",
  "Painting",
  "Crafting",
  "Sewing",
  "Computer",
  "Laptop",
  "Monitor",
  "Printer",
  "Scanner",
  "Server",
  "Tablet",
];
